apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otel-collector-tmp
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
