version: '3.8'

services:
  service-a:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    env_file:
      - .env
    environment:
      SERVICE_NAME: "service-a"
      WEB_SERVER_PORT: ":8081"
      SERVICE2_URL: "http://service-b:8082"
      END: 0
      TEST_DELAY: 1
      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      INSECURE_OTEL_COLLECTOR: true
      LOG_PATH: "/var/log/app.log"
      LOG_FORMAT: "json"
    ports:
      - "8081:8081"
    volumes:
      - ./logs/service-a:/var/log
    depends_on:
      - otel-collector
      - db

  service-b:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    env_file:
      - .env
    environment:
      SERVICE_NAME: "service-b"
      WEB_SERVER_PORT: ":8082"
      SERVICE2_URL: "http://service-c:8083"
      END: 0
      TEST_DELAY: 2
      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      INSECURE_OTEL_COLLECTOR: true
      LOG_PATH: "/var/log/app.log"
      LOG_FORMAT: "logFmt"
    ports:
      - "8082:8082"
    volumes:
      - ./logs/service-b:/var/log
    depends_on:
      - otel-collector
      - db

  service-c:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    env_file:
      - .env
    environment:
      SERVICE_NAME: "service-c"
      WEB_SERVER_PORT: ":8083"
      SERVICE2_URL: "http://service-a:8081"
      END: 1
      TEST_DELAY: 2
      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      INSECURE_OTEL_COLLECTOR: true
      LOG_PATH: "/var/log/app.log"
      LOG_FORMAT: "logFmt"
    ports:
      - "8083:8083"
    volumes:
      - ./logs/service-c:/var/log
    depends_on:
      - otel-collector
      - db

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./logs/service-a:/var/log/service-a
      - ./logs/service-b:/var/log/service-b
      - ./logs/service-c:/var/log/service-c
    ports:
      - "1888:1888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
      - "55679:55679"
    depends_on:
      - prometheus
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
      
  grafana:
    image: grafana/grafana:12.1.1
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - jaeger
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
  
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/db/init:/docker-entrypoint-initdb.d
      - ./.docker/db/data:/data

volumes:
  grafana-data:
        