storage:
  type: elasticsearch
  options:
    es:
      server-urls: http://elasticsearch:9200
  volumeClaimTemplate:
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
      storageClassName: gp2
