apiVersion: 1
datasources:
  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: true
    jsonData:
      tracesToLogsV2:
        customQuery: true
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: false
        query: '{service_name=~".+"} | traceId="$${__trace.traceId}"'
        spanEndTimeShift: 2m
        spanStartTimeShift: -2m
        tags:
          - key: ""
            value: ""
      tracesToMetrics:
        datasourceUid: prometheus
        queries:
          - name: Metrics By Trace
            query: '{traceId="$${__trace.traceId}"}'
          - name: Metrics By Span
            query: '{spanId="$${__span.spanId}"}'
        spanEndTimeShift: 2m
        spanStartTimeShift: -2m
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100