receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    include_file_path: true
    include: [/var/log/service-a/*.log,/var/log/service-b/*.log,/var/log/service-c/*.log]   # Caminho dos arquivos de log
    start_at: end
    operators:
      - type: json_parser
        parse_from: body
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S%Z'
        severity:
          parse_from: attributes.level
        agent:
          parse_from: attributes.agent

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
    
exporters:
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

processors:
  batch:
  resource:
    attributes:
      - action: insert
        key: agent
        value: otel-collector
      - action: insert
        key: loki.attribute.labels
        value: service_name
  transform:
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["service.name"], attributes["service_name"])

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [filelog]
      exporters: [otlphttp/logs]
      processors: [transform, batch, resource]
