allInOne:
  enabled: true
  replicas: 1
  image:
    repository: jaegertracing/all-in-one
    tag: "" # use default or especifique
  service:
    type: LoadBalancer # ou ClusterIP/NodePort conforme necessidade

storage:
  type: memory

provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false

collector:
  enabled: false

query:
  enabled: false

agent:
  enabled: false

ingester:
  enabled: false