flowchart TD
    subgraph Net 
        istio[Istio]
    end

    subgraph Aplicação
        app[Aplicação Go]
        file[File logs]
    end

    subgraph Observabilidade
        otel[OpenTelemetry Collector]
        jaeger[Jaeger]
        prometheus[Prometheus]
        loki[Loki]
    end

    subgraph Visualização
        grafana[Grafana]
    end

    app -- Logs --> file
    istio -- Métricas/Traces --> app
    istio -- Métricas/Traces --> otel
    file -- Logs --> otel
    otel -- Traces --> jaeger
    otel -- Métricas --> prometheus
    otel -- Logs --> loki
    

    grafana  -.-> prometheus
    grafana  -.-> jaeger
    grafana  -.-> loki